### ISSUE TITLE
add real testimonials

### ISSUE THREAD

**Issue by Maxhodges** [white-rabbit-japan/wreHomePage#7]

**Comment by SabinaFischer** [comment]
These are the two most recent feedback I saved:

Posted on Facebook by Melissa Utz so we can use without permission? I think I'll message them anyway to ask what name to use for them. 
"You guys are AMAZING. Super prompt and friendly customer service. I was so nervous to place my order because I'd never gone through a buying service before, but your system is so efficient, fast and reasonable that all my fears were laid to rest. I will recommend you to everyone. Thank you so much!!"

Could edit down to:
"You guys are AMAZING. Super prompt and friendly customer service. I was so nervous to place my order because I'd never gone through a buying service before, but your system is so efficient, fast and reasonable that all my fears were laid to rest."

or if too long still.. "I was so nervous to place my order because I'd never gone through a buying service before, but your system is so efficient, fast and reasonable that all my fears were laid to rest."

Only problem is they are talking about our old system...

Then this one was an email from Michael Sicuranza so I'll contact them and ask if we can use it: 
"I just got my two packages yesterday in excellent condition and the shipping was fast! It was a lot of fun opening my packages with the preorder bonuses from Japan. We don't get great stuff like that here in the U.S. Thanks for being the bridge for the great limited edition products. As a first time buyer, I am very pleased with your service and you can bet I'll be using you guys much more in the future! Thanks again!"

Edit down to: "I just got my two packages yesterday in excellent condition and the shipping was fast! It was a lot of fun opening my packages with the preorder bonuses from Japan. Thanks for being the bridge for the great limited edition products." (could also cut out middle sentence?)

I think they each highlight something different about the service so are a good starting point.

Edit: contacted them both about using the quotes.

**Comment by Maxhodges** [comment]
@SabinaFischer can you get their country and twitter handle?
would help give it credibility if they are ok with that

**Comment by Maxhodges** [comment]
@sabinaFischer

remembered we also have all these on whiterabbitexpress.com. I moved them to Docs
http://support.whiterabbitexpress.com/article/65-testimonials

I'll work in the Gizmodo one for now

**Comment by Maxhodges** [comment]
added some twitter testimonials
